# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleIosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.5'
  
  pod 'analytics', :path => '../analytics'
  pod 'Firebase', "~> 7.4.0"
  pod 'FirebaseAnalytics', "~> 7.4.0"

  target 'sampleIosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleIosAppUITests' do
    # Pods for testing
  end
end
